// Generated by CoffeeScript 2.7.0
(function() {
  // OpDumper.coffee
  var OpDumper, assert, croak, defined, fs, indented, isString, notdefined, range, undef, undented;

  fs = require("fs");

  ({undef, defined, notdefined, isString, assert, croak, range, indented, undented} = require('./vllu.js'));

  OpDumper = class OpDumper {
    constructor(name) {
      this.name = name;
      this.level = 0;
      this.lLines = [];
    }

    // ..........................................................
    incLevel() {
      return this.level += 1;
    }

    decLevel() {
      return this.level -= 1;
    }

    // ..........................................................
    out(str) {
      this.lLines.push("  ".repeat(this.level) + str);
    }

    // ..........................................................
    outBC(lByteCodes) {
      this.out('OPCODES:');
      this.out(lByteCodes.map((x) => {
        return x.toString();
      }).join(' '));
    }

    // ..........................................................
    write() {
      var fileName;
      fileName = `./${this.name}.opcodes.txt`;
      console.log(`Writing opcodes to ${fileName}`);
      fs.writeFileSync(fileName, lLines.join("\n"));
    }

  };

  // --------------------------------------------------------------------------
  module.exports = {OpDumper};

}).call(this);
