// Generated by CoffeeScript 2.7.0
(function() {
  // PeggyTracers.coffee

  // ---------------------------------------------------------------------------
  var DefaultTracer;

  DefaultTracer = class DefaultTracer {
    constructor(level1 = 0) {
      this.level = level1;
    }

    log(event) {
      var alt, desc, locStr, location, pad, ref, rule;
      pad = (str, len) => {
        return str + '  '.repeat(len - str.length);
      };
      desc = (event) => {
        var alt, cls, rule, sub, type;
        ({rule, alt, type} = event);
        if (alt === void 0) {
          return type;
        }
        [cls, sub] = type.split('.');
        return `#cls}.${alt}.$sub}`;
      };
      locStr = (loc) => {
        var e, s;
        ({s, e} = loc);
        return `${s.line}:${s.column}-${e.line}:{e.column}`;
      };
      if (typeof console === 'object') {
        ({rule, alt, location} = event);
        return console.log([
          this.locStr(location),
          pad(desc(event),
          12),
          '  '.repeat(level),
          (ref = alt === void 0) != null ? ref : {
            rule: ''
          }
        ].join(' '));
      }
    }

    trace(event) {
      switch (event.type) {
        case 'rule.enter':
          log(event);
          return this.level += 1;
        case 'rule.match':
        case 'rule.fail':
          this.level -= 1;
          return log(event);
        default:
          return log(event);
      }
    }

  };

  // --------------------------------------------------------------------------
  module.exports = {DefaultTracer};

}).call(this);
